// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - \n'
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - \n'
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPF0kOgZIic7UQBqO9Spae-rRPf_p-k0',
    appId: '1:369780198504:web:2f5513c3be4817b3467fdd',
    messagingSenderId: '369780198504',
    projectId: 'neuramess',
    authDomain: 'neuramess.firebaseapp.com',
    storageBucket: 'neuramess.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUx0DRz24fsx9hr5HXmkVBYhXN0LVWClI',
    appId: '1:369780198504:android:344903256cf45791467fdd',
    messagingSenderId: '369780198504',
    projectId: 'neuramess',
    storageBucket: 'neuramess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoJaugF87DqEQcM8wlt7TraodRgTxD65o',
    appId: '1:369780198504:ios:96e1738dc0ebbcd1467fdd',
    messagingSenderId: '369780198504',
    projectId: 'neuramess',
    storageBucket: 'neuramess.firebasestorage.app',
    androidClientId: '369780198504-vvmccl8ir4j1hspd2f6ts2jd6hiu6vg2.apps.googleusercontent.com',
    iosClientId: '369780198504-f35clnvb64calpq18d3emioqnr2b3kfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoJaugF87DqEQcM8wlt7TraodRgTxD65o',
    appId: '1:369780198504:ios:96e1738dc0ebbcd1467fdd',
    messagingSenderId: '369780198504',
    projectId: 'neuramess',
    storageBucket: 'neuramess.firebasestorage.app',
    iosBundleId: 'com.example.mess.RunnerTests',
    androidClientId: '369780198504-210cvvucdqkltn07m7qv0tadpdlmnslp.apps.googleusercontent.com',
    iosClientId: '369780198504-210cvvucdqkltn07m7qv0tadpdlmnslp.apps.googleusercontent.com',
  );
}